language: c

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq zlib1g-dev libbz2-dev liblzma-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
