os:
  - linux
  - osx

language: c

compiler:
  - gcc

addons:
  apt:
    packages:
      - zlib1g-dev
      - libbz2-dev
      - liblzma-dev

before_script:
  - mkdir build
  - cd build
  - cmake .. -DENABLE_7Z=ON

script: make
