
os: Visual Studio 2015

platform:
  - x86
  - x64

before_build:
  - md build
  - cd build
  - cmake .. -DENABLE_7Z=ON -G"Visual Studio 14 2015"

build_script:
  - cmake --build build

artifacts:
  - path: unarr.dll
  - path: unarr.h
